### ISSUE TITLE
关于360、百度等软件

### ISSUE THREAD

**Issue by cnyaojin** [SoDa-GitHub/SSRR-Windows#7]
大神，之前确实装过360安全卫士，但是已经卸载掉了。

残余实在不好找，能否提供一个清理360残余的软件或方法，以便ssr可以运行起来。

百度同上

谢谢

**Comment by zxlzy** [comment]
我今天一升级软件也弹出来这个。主要是不升级老有升级提示。蛋疼。刚才看了一下代码。。其实作者不喜欢不用就是了。也不知道哪来的怨念。直接称为病毒。。已经卸载的话打开注册表搜索"360Safe","ZhuDongFangYu","2345SoftSvc","2345RTProtect","BaiduAnSvc","BaiduHips"删除掉就行。

**Comment by SoDa-GitHub** [comment]
@zxlzy 360的傻逼用户请使用https://github.com/shadowsocksrr/shadowsocksr-csharp
这个版本，既不会有升级提升也不会屏蔽360。不知道哪来的弱智，病毒都分不清楚。
